spring:
  application:
    name: virtex
  profiles:
    group:
      "local-h2": "local"
application:
  version: 0.1
---
spring:
  datasource:
    url: jdbc:mysql://${db.host}:${db.port}/${db.name}?useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: ${db.username}
    password: ${db.password}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: com.meghrajswami.virtex.CustomMysqlDialect
    show-sql: true
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
    serialization:
      indent_output: true
server:
  error:
    whitelabel:
      enabled: false
virtex:
  instruments_config:
    instruments-example.conf
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
#  resources:
#    cache-period: 5184000
#    chain:
#      cache: true
#      strategy:
#        fixed:
#          enabled: true
##          paths: /**/*.js,/**/*.map
#          version: ${application.version}
#        content:
#          enabled: true
#      html-application-cache: true
#  data:
#    elasticsearch:
#      cluster-nodes: localhost:9300
#server:
#  compression:
#    enabled: true
#    mime-types: text/html,text/xml,text/plain,text/css,application/json,application/javascript,application/xml,image/png
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

---
spring:
  config:
    activate:
      on-profile: local-h2
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
#    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
---
spring:
  config:
    activate:
      on-profile: eb
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}?useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: ${rds.username}
    password: ${rds.password}
  web:
    resources:
      chain:
        strategy:
          fixed:
            enabled: true
            version: ${application.version}
          content:
            enabled: true
        cache: true
      cache:
        period: 5184000
#security:
#  require-ssl: true
server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/json,application/javascript,application/xml,image/png
  forward-headers-strategy: native
---
spring:
  config:
    activate:
      on-profile: heroku
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:${jawsdb.url}?useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username:
    password:
  web:
    resources:
      chain:
        cache: true
        strategy:
          fixed:
            enabled: true
            version: ${application.version}
          content:
            enabled: true
      cache:
        period: 5184000
#security:
#  require-ssl: true
server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/json,application/javascript,application/xml,image/png
  forward-headers-strategy: native
