application:
  version: 0.1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/virtex?useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: virtex
    password: virtex
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: com.meghrajswami.virtex.CustomMysqlDialect
    show-sql: true
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
    serialization:
      indent_output: true
server:
  error:
    whitelabel:
      enabled: false
virtex:
  instruments-config:
    instruments-example.conf
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
---
spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
#  resources:
#    cache-period: 5184000
#    chain:
#      cache: true
#      strategy:
#        fixed:
#          enabled: true
##          paths: /**/*.js,/**/*.map
#          version: ${application.version}
#        content:
#          enabled: true
#      html-application-cache: true
#  data:
#    elasticsearch:
#      cluster-nodes: localhost:9300
#server:
#  compression:
#    enabled: true
#    mime-types: text/html,text/xml,text/plain,text/css,application/json,application/javascript,application/xml,image/png
---
spring:
  profiles: eb
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}?useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: ${rds.username}
    password: ${rds.password}
  resources:
    cache-period: 5184000
    chain:
      cache: true
      strategy:
        fixed:
          enabled: true
#          paths: /**/*.js,/**/*.map
          version: ${application.version}
        content:
          enabled: true
      html-application-cache: true
#security:
#  require-ssl: true
server:
  use-forward-headers: true
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/json,application/javascript,application/xml,image/png
---
spring:
  profiles: heroku
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:${jawsdb.url}?useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username:
    password:
  resources:
    cache-period: 5184000
    chain:
      cache: true
      strategy:
        fixed:
          enabled: true
#          paths: /**/*.js,/**/*.map
          version: ${application.version}
        content:
          enabled: true
      html-application-cache: true
#security:
#  require-ssl: true
server:
  use-forward-headers: true
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/json,application/javascript,application/xml,image/png
